export const mockEvents = [
    {
        id: "1",
        name: "Rock Night Festival",
        category: "Music",
        address: "123 Rock Street, Paris",
        date: "2025-07-20",
        time: "20:00",
        tickets: {
            VIP: { price: 100, currency: "eur", quantity: 50, availability: 10 },
            Standard: { price: 50, currency: "eur", quantity: 200, availability: 20 },
        },
        description: "An amazing night of rock music!",
        image: "/images/img.png",
    },
    {
        id: "2",
        name: "Jazz in the Park",
        category: "Jazz",
        address: "Green Park, Lyon",
        date: "2025-06-15",
        time: "20:00",
        tickets: {
            VIP: { price: 80, currency: "eur", quantity: 30, availability: 5 },
            Standard: { price: 40, currency: "eur", quantity: 100, availability: 15 },
        },
        description: "Experience the best jazz vibes in an open-air concert.",
        image: "/images/img.png",
    },
    {
        id: "3",
        name: "Lady Gaga in Singapore",
        category: "Pop",
        address: "National Stadium, Singapore",
        date: "2024-05-19",
        time: "20:00",
        tickets: {
            VIP: { price: 299, currency: "eth", quantity: 100, availability: 20 },
            Standard: { price: 150, currency: "eth", quantity: 500, availability: 50 },
        },
        description: "A spectacular performance by Lady Gaga at the National Stadium.",
        image: "/25sg_ladygaga.jpg",
    },
    {
        id: "4",
        name: "Taylor Swift | The Eras Tour",
        category: "Pop",
        address: "Madison Square Garden, New York",
        date: "2024-03-15",
        time: "20:00",
        tickets: {
            VIP: { price: 299, currency: "usd", quantity: 150, availability: 30 },
            Standard: { price: 120, currency: "usd", quantity: 600, availability: 100 },
        },
        description: "Taylor Swift brings her legendary Eras Tour to New York!",
        image: "/img.png",
    },
    {
        id: "5",
        name: "Ed Sheeran World Tour",
        category: "Pop",
        address: "Wembley Stadium, London",
        date: "2024-03-20",
        time: "20:00",
        tickets: {
            VIP: { price: 189, currency: "eur", quantity: 80, availability: 10 },
            Standard: { price: 90, currency: "eur", quantity: 400, availability: 50 },
        },
        description: "Experience Ed Sheeran live in one of the biggest concerts of the year.",
        image: "/img.png",
    },
    {
        id: "6",
        name: "Metallica",
        category: "Rock",
        address: "Rose Bowl, Los Angeles",
        date: "2024-04-05",
        time: "20:00",
        tickets: {
            VIP: { price: 250, currency: "usd", quantity: 120, availability: 15 },
            Standard: { price: 110, currency: "usd", quantity: 500, availability: 75 },
        },
        description: "Metal legends Metallica return with an unforgettable live show.",
        image: "/img.png",
    },
    {
        id: "7",
        name: "The Weeknd",
        category: "R&B",
        address: "United Center, Chicago",
        date: "2024-04-15",
        time: "20:00",
        tickets: {
            VIP: { price: 225, currency: "eth", quantity: 90, availability: 10 },
            Standard: { price: 100, currency: "eth", quantity: 450, availability: 0 },
        },
        description: "The Weeknd brings his chart-topping hits to Chicago!",
        image: "/img.png",
    },
    {
        id: "8",
        name: "Bad Bunny",
        category: "Latin",
        address: "American Airlines Arena, Miami",
        date: "2024-05-01",
        time: "20:00",
        tickets: {
            VIP: { price: 275, currency: "eur", quantity: 110, availability: 100 },
            Standard: { price: 130, currency: "eur", quantity: 500, availability: 10 },
        },
        description: "Bad Bunny’s electrifying Latin beats take over Miami!",
        image: "/img.png",
    },
    {
        id: "9",
        name: "Drake",
        category: "Hip Hop",
        address: "Scotiabank Arena, Toronto",
        date: "2024-05-10",
        time: "20:00",
        tickets: {
            VIP: { price: 295, currency: "usd", quantity: 100, availability: 5 },
            Standard: { price: 140, currency: "usd", quantity: 450, availability: 20 },
        },
        description: "Drake’s explosive live performance at Scotiabank Arena!",
        image: "/img.png",
    },
];
